"""add_canvas_inserts_table

Revision ID: bf2254b8bf1b
Revises: c73a24e29a10
Create Date: 2026-03-26 10:09:00.068513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2254b8bf1b'
down_revision: Union[str, None] = 'c73a24e29a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas_inserts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_topic_id', sa.Integer(), nullable=False),
    sa.Column('insert_topic_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insert_topic_id'], ['curriculum_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['curriculum_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvas_inserts_id'), 'canvas_inserts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canvas_inserts_id'), table_name='canvas_inserts')
    op.drop_table('canvas_inserts')
    # ### end Alembic commands ###
