"""add slot_type to subject

Revision ID: c73a24e29a10
Revises: d2707ecf67ae
Create Date: 2026-03-25 10:04:44.148778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73a24e29a10'
down_revision: Union[str, None] = 'd2707ecf67ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('slot_type', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'slot_type')
    # ### end Alembic commands ###
