"""Add end_date to Subject

Revision ID: d2707ecf67ae
Revises: e1d26a8632d1
Create Date: 2026-03-23 08:47:16.361239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2707ecf67ae'
down_revision: Union[str, None] = 'e1d26a8632d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'end_date')
    # ### end Alembic commands ###
