alter table app.children
  add constraint uq_children_id_owner unique (id, owner_id);

alter table app.documents
  add constraint uq_documents_id_owner unique (id, owner_id);

create table app.pdf_page_annotations (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references app.family_accounts(user_id) on delete cascade,
  child_id integer not null,
  document_id integer not null,
  page_number integer not null,
  strokes jsonb not null default '[]'::jsonb,
  revision integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pdf_page_annotations_child_owner_fkey
    foreign key (child_id, owner_id)
    references app.children(id, owner_id)
    on delete cascade,
  constraint pdf_page_annotations_document_owner_fkey
    foreign key (document_id, owner_id)
    references app.documents(id, owner_id)
    on delete cascade,
  constraint uq_pdf_page_annotations_page
    unique (owner_id, child_id, document_id, page_number),
  constraint ck_pdf_page_annotations_page_positive check (page_number > 0),
  constraint ck_pdf_page_annotations_revision_positive check (revision > 0),
  constraint ck_pdf_page_annotations_strokes_array check (jsonb_typeof(strokes) = 'array')
);

create index ix_pdf_page_annotations_owner_id
  on app.pdf_page_annotations(owner_id);

create index ix_pdf_page_annotations_document_owner
  on app.pdf_page_annotations(document_id, owner_id);

alter table app.pdf_page_annotations enable row level security;

create policy "deny direct access"
  on app.pdf_page_annotations
  for all
  using (false)
  with check (false);

comment on table app.pdf_page_annotations is
  'Editable per-child vector strokes layered over a physical PDF page; source Blob documents remain unchanged.';
