-- Hosted schema for the private Homeschooling deployment.
create schema if not exists app;
revoke all on schema app from public;

create table if not exists app.family_accounts (
  user_id uuid primary key,
  created_at timestamptz not null default now()
);
create table if not exists app.children (
  id integer generated by default as identity primary key,
  owner_id uuid not null references app.family_accounts(user_id) on delete cascade,
  name varchar(100) not null, nickname varchar(50), color varchar(7) not null default '#6B9E8A',
  grade_year varchar(20), created_at timestamptz not null default now()
);
create table if not exists app.subjects (
  id integer generated by default as identity primary key,
  child_id integer not null references app.children(id) on delete cascade,
  name varchar(100) not null, weight double precision default 1.0, slot_type varchar(1) default 'A',
  end_date date, created_at timestamptz not null default now()
);
create table if not exists app.documents (
  id integer generated by default as identity primary key,
  owner_id uuid not null references app.family_accounts(user_id) on delete cascade,
  blob_path varchar(600) not null unique, original_filename varchar(255) not null,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 262144000),
  page_count integer not null check (page_count > 0), sha256 varchar(64), status varchar(30) not null default 'ready',
  created_at timestamptz not null default now()
);
create table if not exists app.curriculum_topics (
  id integer generated by default as identity primary key,
  subject_id integer not null references app.subjects(id) on delete cascade,
  title varchar(300) not null, page_start integer not null, page_end integer not null,
  complexity integer default 1, completed boolean default false, language varchar(10),
  chapter_order integer default 0, pdf_filename varchar(255), document_id integer references app.documents(id) on delete set null,
  pdf_page_offset integer default 0, is_core boolean default true, created_at timestamptz not null default now(),
  check (page_start >= 0 and page_end >= page_start)
);
create table if not exists app.time_windows (
  id integer generated by default as identity primary key,
  child_id integer not null references app.children(id) on delete cascade,
  weekday integer not null check (weekday between 0 and 6), start_time varchar(5) not null, end_time varchar(5) not null
);
create table if not exists app.blocked_days (
  id integer generated by default as identity primary key,
  owner_id uuid not null references app.family_accounts(user_id) on delete cascade,
  child_id integer references app.children(id) on delete cascade, date date not null,
  block_type varchar(20) not null, note varchar(255), created_at timestamptz not null default now()
);
create table if not exists app.scheduled_slots (
  id integer generated by default as identity primary key,
  child_id integer not null references app.children(id) on delete cascade,
  subject_id integer not null references app.subjects(id) on delete cascade,
  topic_id integer references app.curriculum_topics(id) on delete cascade,
  date date not null, time_start varchar(5) not null, time_end varchar(5) not null,
  page_from integer, page_to integer
);
create table if not exists app.completions (
  id integer generated by default as identity primary key,
  slot_id integer not null unique references app.scheduled_slots(id) on delete cascade,
  completed_at timestamptz not null default now()
);
create table if not exists app.canvas_inserts (
  id integer generated by default as identity primary key,
  parent_topic_id integer not null references app.curriculum_topics(id) on delete cascade,
  insert_topic_id integer not null references app.curriculum_topics(id) on delete cascade,
  position integer default 0, created_at timestamptz not null default now()
);
create table if not exists app.canvas_ai_content (
  id integer generated by default as identity primary key,
  topic_id integer not null references app.curriculum_topics(id) on delete cascade,
  page_start integer not null, page_end integer not null, content_type varchar(20) not null, content text not null,
  created_at timestamptz not null default now(),
  unique(topic_id, page_start, page_end, content_type)
);
create table if not exists app.app_settings (
  id integer generated by default as identity primary key,
  owner_id uuid not null references app.family_accounts(user_id) on delete cascade,
  key varchar(100) not null, value varchar(500) not null, updated_at timestamptz not null default now(),
  unique(owner_id, key)
);
create index if not exists children_owner_idx on app.children(owner_id);
create index if not exists documents_owner_idx on app.documents(owner_id);
create index if not exists documents_sha_idx on app.documents(sha256);
create index if not exists topics_document_idx on app.curriculum_topics(document_id);
create index if not exists slots_child_date_idx on app.scheduled_slots(child_id, date);
create index if not exists blocked_days_owner_date_idx on app.blocked_days(owner_id, date);
create index if not exists canvas_ai_topic_idx on app.canvas_ai_content(topic_id);

-- app is deliberately absent from Supabase's exposed schemas. RLS remains
-- enabled as a second barrier if that configuration ever changes.
alter table app.family_accounts enable row level security;
alter table app.children enable row level security;
alter table app.subjects enable row level security;
alter table app.documents enable row level security;
alter table app.curriculum_topics enable row level security;
alter table app.time_windows enable row level security;
alter table app.blocked_days enable row level security;
alter table app.scheduled_slots enable row level security;
alter table app.completions enable row level security;
alter table app.canvas_inserts enable row level security;
alter table app.canvas_ai_content enable row level security;
alter table app.app_settings enable row level security;
